# Generated by Django 3.2.8 on 2021-12-04 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.CharField(max_length=200)),
                ('end', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('races', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrida.races')),
            ],
        ),
    ]
