# Generated by Django 3.2.8 on 2021-12-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='races',
        ),
        migrations.DeleteModel(
            name='Races',
        ),
    ]
